// Text of the five sample books, in English and German.
// Original works written for PDBOOK; free to use and share.

export const TEXT = {
  /* ====================================================================== */
  en: {
    publisher: 'PDBOOK Sample Press',
    cartographer: {
      file: '01-the-cartographer-of-small-islands.pdf',
      title: 'The Cartographer of Small Islands',
      coverTop: 'THE CARTOGRAPHER',
      coverBottom: 'of Small Islands',
      kicker: 'A SHORT STORY',
      chapter: 'CHAPTER',
      plate: 'Plate {n}. An island, surveyed at low tide.',
      chapters: [
        ['The Drawer', [
          'The harbour master kept a drawer of maps that nobody had asked for. Each one showed an island no larger than a kitchen table, drawn with the same care as a continent.',
          'He had started the habit as a boy, when his father let him hold the end of the measuring chain. Now the drawer would barely close, and he had begun a second one.',
          'There were islands shaped like spoons and islands shaped like sleeping dogs. One, which he loved most, was the exact outline of his late wife’s left hand.',
        ]],
        ['Low Tide', [
          'He measured them at low tide with a knotted rope and a borrowed compass, wading out with his trousers rolled and his notebook tucked inside his hat.',
          'Low tide was honest. It showed the rocks the sea preferred to hide, and the long ribs of sand that joined one small island to the next for an hour or two each day.',
          'On those mornings the harbour looked less like water and more like a sentence that had not been finished.',
        ]],
        ['Ink and Lamp', [
          'In the evenings he sat by the lamp and inked every rock, every tuft of grass, every place where a gull had decided to nest.',
          'He used three nibs and one bottle of ink a year. The fine nib was for coastlines, the broad one for names, and the middle one for everything he was not yet sure about.',
          'He never used colour. Colour, he said, was a promise the weather would break.',
        ]],
        ['Visitors', [
          'Visitors laughed at first. A map of a rock, they said, was just a rock with extra steps.',
          'Then they began to notice how the small maps made the sea feel smaller too, as if the whole horizon could be folded and carried home in a coat pocket.',
          'A schoolteacher asked for a copy for her classroom. A fisherman asked for the one with the sunken wall, because his nets kept tearing there and now he knew why.',
        ]],
        ['Winter Maps', [
          'In winter the islands vanished under grey water and he redrew them from memory, which was not the same as drawing them wrong.',
          'Memory added a tree where there had only been a hope of one. It moved a rock a little closer to its neighbour, as if the two had grown fond of each other over the summer.',
          'He kept these winter maps in a separate folder, labelled in small letters: Possible.',
        ]],
        ['The Last Island', [
          'The spring he turned eighty, a new island rose a little north of the breakwater: a hump of shingle the storms had built and forgotten.',
          'He measured it slowly, resting between knots. He named it after nobody, which was the kindest name he knew, and he left a corner of the map blank on purpose.',
          'Somewhere, he wrote beneath it, there should always be a little room for the sea to change its mind.',
        ]],
      ],
      more: [
        'The sea did not care for his maps, and he did not ask it to. A map, he believed, was a way of paying attention, and attention was the only rent he could afford.',
        'By the time the tide turned, he would be back on the quay with wet ankles and a page full of numbers, already arguing with himself about the shape of a single stone.',
        'Some days he drew nothing at all. He only watched, which he said was also a kind of drawing, only slower.',
      ],
      backQuote: ['“A map is a promise that', 'somewhere is worth returning to.”'],
    },
    fox: {
      file: '02-the-clockmakers-fox.pdf',
      title: 'The Clockmaker’s Fox',
      coverTitle: 'The Clockmaker’s Fox',
      kicker: 'A PICTURE BOOK',
      pages: [
        'In a town where every roof had a weathervane, there lived an old clockmaker named Ada, who mended clocks that had forgotten how to tick.',
        'One winter night, a small red fox crept into her workshop. It was not looking for food. It was looking for the sound.',
        'Tick, went the clocks on the wall. Tock, went the clocks on the shelf. The fox sat very still and listened with both ears.',
        '“You may stay,” said Ada, “if you help me listen.” So the fox learned which clocks were healthy and which ones limped.',
        'A clock with a sticky spring went tick... ...tock. A clock with a loose gear went ticktickticktock. The fox could hear them all.',
        'Soon people came from every street. “The fox can hear what’s wrong,” they said, and they brought their quiet, broken clocks.',
        'When spring came, the fox stood at the open door for a long time. The forest was ticking too, in its own green way.',
        '“Go on,” said Ada. “But come back when something stops.” And every winter, when the town clocks grew slow, the fox came home.',
      ],
      end: 'The End',
      back: 'For everyone who listens closely.',
    },
    birds: {
      file: '03-a-field-guide-to-imaginary-birds.pdf',
      title: 'A Field Guide to Imaginary Birds',
      coverTop: 'A FIELD GUIDE TO',
      coverTitle: 'Imaginary Birds',
      coverSub: 'Twelve species you will never see',
      introTitle: 'How to Use This Guide',
      intro:
        'Every bird in this book has been observed by at least one person who was not quite paying attention. Each entry lists where the bird is said to live, what it is said to sound like, and the best time to fail to see it.\nReaders are encouraged to keep their own notes in the margins. Sightings cannot be confirmed, but they can be enjoyed.',
      labels: ['Habitat', 'Call', 'Field notes'],
      sightings: 'My sightings:',
      species: [
        ['Teacup Warbler', 'Kitchen windowsills, early morning.', 'A soft clink, like a spoon set down.', 'Only sings when the kettle is about to boil.'],
        ['Lesser Umbrella Heron', 'Bus stops during light drizzle.', 'A papery flap.', 'Stands on one leg and pretends to be closed.'],
        ['Crested Daydream', 'The last row of any classroom.', 'A long, unfinished hum.', 'Vanishes the moment it is named aloud.'],
        ['Library Owl', 'Between the shelves of unread books.', 'A disapproving “hush”.', 'Nests in returned books with bent corners.'],
        ['Copper Lantern Finch', 'Harbours at dusk.', 'A low, warm whistle.', 'Its feathers are said to glow when someone is late home.'],
        ['Paper Swift', 'Above desks near open windows.', 'The rustle of a page turning.', 'Migrates every time a letter is sent.'],
        ['Midnight Plover', 'Empty beaches under a new moon.', 'Two notes, then a long pause.', 'Visible only out of the corner of the eye.'],
        ['Common Somewhere Sparrow', 'Everywhere you are not.', 'A cheerful, distant chirp.', 'The most widespread imaginary bird.'],
        ['Velvet Thunderbird', 'Hilltops before a storm.', 'A rumble felt in the chest.', 'Children report it more often than adults.'],
        ['Garden Muddle', 'Under hedges, near lost gloves.', 'A confused, three-note question.', 'Often found sitting on the thing you are looking for.'],
        ['Silver-Tongued Rumourbird', 'Markets, staircases, doorways.', 'A whisper that changes each time.', 'No two reports agree, which proves its existence.'],
        ['Quiet Hour Wren', 'Wherever someone is reading.', 'None. It is the silence itself.', 'You are probably near one now.'],
      ],
      back: 'Keep looking up.',
    },
    bread: {
      file: '04-bread-and-salt.pdf',
      title: 'Bread & Salt: Simple Recipes',
      coverTitle: 'BREAD & SALT',
      coverSub: 'Simple recipes for ordinary days',
      kicker: 'A PDBOOK SAMPLE',
      contents: 'Contents',
      contentsNote: 'Nothing here is difficult. These are the recipes you make when you want something good without making a fuss about it.',
      ingredients: 'INGREDIENTS',
      method: 'METHOD',
      recipes: [
        ['Skillet Flatbread', 'Makes 6', ['250 g plain flour', '1 tsp salt', '1 tsp baking powder', '150 ml warm water', '2 tbsp olive oil'],
          ['Mix the flour, salt and baking powder in a bowl.', 'Add the water and oil and stir until a soft dough forms.', 'Knead for two minutes, then rest it under a towel for 15 minutes.', 'Divide into six balls and roll each one thin.', 'Cook in a dry, hot pan for about a minute per side, until puffed and spotted brown.']],
        ['Plain Tomato Soup', 'Serves 4', ['2 tbsp olive oil', '1 onion, chopped', '2 cloves garlic, sliced', '800 g canned tomatoes', '500 ml vegetable stock', 'Salt and pepper'],
          ['Soften the onion in the oil over medium heat for 8 minutes.', 'Add the garlic and cook one minute more.', 'Add the tomatoes and stock and simmer for 20 minutes.', 'Blend until smooth and season to taste.', 'Serve with flatbread for dipping.']],
        ['Lemon Rice', 'Serves 3', ['200 g long-grain rice', '1 tbsp butter or oil', '1 lemon, zest and juice', 'A handful of parsley', 'Salt'],
          ['Rinse the rice until the water runs clear.', 'Cook it with 400 ml salted water, covered, on low heat for 12 minutes.', 'Turn off the heat and leave it covered for 5 minutes.', 'Fork through the butter, lemon zest and juice.', 'Finish with chopped parsley.']],
        ['Roasted Vegetables', 'Serves 4', ['1 kg mixed vegetables (carrots, peppers, onions, potatoes)', '3 tbsp olive oil', '1 tsp salt', '1 tsp dried thyme'],
          ['Heat the oven to 220 °C.', 'Cut the vegetables into similar-sized pieces.', 'Toss with the oil, salt and thyme on a large tray.', 'Roast for 35 to 40 minutes, turning once, until browned at the edges.']],
        ['Sunday Pancakes', 'Makes 8', ['150 g plain flour', '1 tbsp sugar', '2 tsp baking powder', 'A pinch of salt', '1 egg', '200 ml milk', '1 tbsp melted butter'],
          ['Whisk the dry ingredients together.', 'Beat the egg, milk and butter in a jug.', 'Pour the wet into the dry and stir until just combined; a few lumps are fine.', 'Cook ladlefuls in a lightly oiled pan until bubbles appear, then flip.', 'Keep warm in a low oven until all are cooked.']],
        ['Oat Biscuits', 'Makes 16', ['100 g butter', '75 g brown sugar', '1 tbsp honey', '125 g rolled oats', '100 g plain flour', '1/2 tsp baking soda'],
          ['Heat the oven to 180 °C and line a tray.', 'Melt the butter, sugar and honey together.', 'Stir in the oats, flour and baking soda.', 'Roll into walnut-sized balls and flatten slightly on the tray.', 'Bake for 12 minutes, until golden. Cool before eating.']],
      ],
      back: 'Cook simply. Share generously.',
    },
    poems: {
      file: '05-small-hours.pdf',
      title: 'Small Hours: Twelve Short Poems',
      coverTitle: 'Small Hours',
      kicker: 'TWELVE SHORT POEMS',
      poems: [
        ['Kettle', 'Before the house is quite awake\nthe kettle clears its throat,\nand everything I meant to say\nturns into steam and floats.'],
        ['Lighthouse', 'All night it says one word\nto ships it will not meet:\nhere, here, here—\nas if that were enough to keep.'],
        ['Inventory', 'One cup, one chair, one window,\none slow and patient plant.\nI count them like a sleepless child\nwho counts what she still can’t.'],
        ['Snow', 'The snow came down to listen.\nIt settled on the street\nand held its breath so long that\nthe town forgot its feet.'],
        ['Train', 'A train goes by at two a.m.\nwith no one, I suppose, aboard—\njust lit-up windows, carrying\nthe dark from town to town, toward.'],
        ['Library', 'The books are mostly sleeping.\nA few are reading me.\nI turn a page, and somewhere\na sentence turns to see.'],
        ['Small Hours', 'These are the hours too small for clocks,\nthe ones you hold, not keep:\nthe space between a thought and word,\nthe hallway into sleep.'],
        ['Letter', 'I wrote to you and didn’t send it.\nIt waits inside a drawer,\nwhere unsent letters learn the things\nthat letters are for.'],
        ['Rain on a Skylight', 'Someone is typing on the roof\nin a language made of glass.\nI cannot read a word of it.\nI let the paragraphs pass.'],
        ['Moth', 'The moth is in love with the lamp\nthe way I am with June:\nfoolishly, completely,\nand far too soon.'],
        ['Map', 'My grandfather drew islands\nno bigger than a shoe.\nHe said the smallest places\nare where the sea speaks true.'],
        ['Morning', 'And then the light comes, ordinary,\nand pours itself like tea.\nThe night puts down what it was holding.\nSo, finally, do we.'],
      ],
      back: 'Read slowly. It’s late.',
    },
  },

  /* ====================================================================== */
  de: {
    publisher: 'PDBOOK Beispielverlag',
    cartographer: {
      file: '01-der-kartograf-der-kleinen-inseln.pdf',
      title: 'Der Kartograf der kleinen Inseln',
      coverTop: 'DER KARTOGRAF',
      coverBottom: 'der kleinen Inseln',
      kicker: 'EINE KURZGESCHICHTE',
      chapter: 'KAPITEL',
      plate: 'Tafel {n}. Eine Insel, vermessen bei Ebbe.',
      chapters: [
        ['Die Schublade', [
          'Der Hafenmeister besaß eine Schublade voller Karten, um die ihn niemand gebeten hatte. Jede zeigte eine Insel, nicht größer als ein Küchentisch, gezeichnet mit derselben Sorgfalt wie ein Kontinent.',
          'Angefangen hatte er als Junge, als sein Vater ihn das Ende der Messkette halten ließ. Inzwischen ging die Schublade kaum noch zu, und er hatte eine zweite begonnen.',
          'Es gab Inseln in Form von Löffeln und Inseln in Form schlafender Hunde. Eine, die er am meisten liebte, hatte genau den Umriss der linken Hand seiner verstorbenen Frau.',
        ]],
        ['Ebbe', [
          'Er vermaß sie bei Ebbe mit einem geknoteten Seil und einem geliehenen Kompass. Er watete hinaus, die Hosenbeine hochgekrempelt, das Notizbuch unter dem Hut.',
          'Die Ebbe war ehrlich. Sie zeigte die Felsen, die das Meer lieber versteckte, und die langen Sandrippen, die eine kleine Insel ein, zwei Stunden am Tag mit der nächsten verbanden.',
          'An solchen Morgen sah der Hafen weniger nach Wasser aus als nach einem Satz, der noch nicht zu Ende geschrieben war.',
        ]],
        ['Tinte und Lampe', [
          'Abends saß er bei der Lampe und zeichnete jeden Felsen mit Tinte nach, jedes Grasbüschel, jede Stelle, an der eine Möwe beschlossen hatte zu nisten.',
          'Er brauchte drei Federn und ein Tintenfass im Jahr. Die feine Feder war für Küstenlinien, die breite für Namen und die mittlere für alles, worüber er sich noch nicht sicher war.',
          'Farbe benutzte er nie. Farbe, sagte er, sei ein Versprechen, das das Wetter brechen würde.',
        ]],
        ['Besucher', [
          'Die Besucher lachten zuerst. Eine Karte von einem Felsen, sagten sie, sei doch nur ein Felsen mit Umweg.',
          'Dann merkten sie, wie die kleinen Karten auch das Meer kleiner wirken ließen, als könne man den ganzen Horizont zusammenfalten und in der Manteltasche nach Hause tragen.',
          'Eine Lehrerin bat um eine Kopie für ihr Klassenzimmer. Ein Fischer wollte die mit der versunkenen Mauer, weil seine Netze dort immer rissen und er nun wusste, warum.',
        ]],
        ['Winterkarten', [
          'Im Winter verschwanden die Inseln unter grauem Wasser, und er zeichnete sie aus dem Gedächtnis neu, was nicht dasselbe war, wie sie falsch zu zeichnen.',
          'Das Gedächtnis fügte einen Baum hinzu, wo nur die Hoffnung auf einen gewesen war. Es rückte einen Felsen ein wenig näher an seinen Nachbarn, als hätten die beiden sich über den Sommer liebgewonnen.',
          'Diese Winterkarten bewahrte er in einer eigenen Mappe auf, beschriftet in kleinen Buchstaben: Möglich.',
        ]],
        ['Die letzte Insel', [
          'In dem Frühling, in dem er achtzig wurde, stieg ein wenig nördlich der Mole eine neue Insel auf: ein Kieshügel, den die Stürme gebaut und dann vergessen hatten.',
          'Er vermaß sie langsam und ruhte zwischen den Knoten aus. Er benannte sie nach niemandem, dem freundlichsten Namen, den er kannte, und ließ absichtlich eine Ecke der Karte leer.',
          'Irgendwo, schrieb er darunter, sollte immer ein wenig Platz sein, damit das Meer es sich anders überlegen kann.',
        ]],
      ],
      more: [
        'Das Meer kümmerte sich nicht um seine Karten, und er verlangte es auch nicht. Eine Karte, glaubte er, war eine Art, aufmerksam zu sein, und Aufmerksamkeit war die einzige Miete, die er sich leisten konnte.',
        'Wenn die Flut zurückkam, stand er wieder auf dem Kai, mit nassen Knöcheln und einer Seite voller Zahlen, und stritt schon mit sich selbst über die Form eines einzigen Steins.',
        'An manchen Tagen zeichnete er gar nichts. Er schaute nur zu, und das, sagte er, sei auch eine Art zu zeichnen, nur langsamer.',
      ],
      backQuote: ['„Eine Karte ist ein Versprechen, dass', 'es sich lohnt, irgendwohin zurückzukehren.“'],
    },
    fox: {
      file: '02-der-fuchs-des-uhrmachers.pdf',
      title: 'Der Fuchs des Uhrmachers',
      coverTitle: 'Der Fuchs des Uhrmachers',
      kicker: 'EIN BILDERBUCH',
      pages: [
        'In einer Stadt, in der auf jedem Dach eine Wetterfahne stand, lebte eine alte Uhrmacherin namens Ada. Sie reparierte Uhren, die vergessen hatten, wie man tickt.',
        'In einer Winternacht schlich ein kleiner roter Fuchs in ihre Werkstatt. Er suchte kein Futter. Er suchte das Geräusch.',
        'Tick, machten die Uhren an der Wand. Tack, machten die Uhren im Regal. Der Fuchs saß ganz still und lauschte mit beiden Ohren.',
        '„Du darfst bleiben“, sagte Ada, „wenn du mir beim Hören hilfst.“ So lernte der Fuchs, welche Uhren gesund waren und welche humpelten.',
        'Eine Uhr mit klebriger Feder machte tick … … tack. Eine Uhr mit lockerem Zahnrad machte ticktickticktack. Der Fuchs hörte sie alle.',
        'Bald kamen Leute aus allen Straßen. „Der Fuchs hört, was fehlt“, sagten sie und brachten ihre stillen, kaputten Uhren.',
        'Als der Frühling kam, stand der Fuchs lange an der offenen Tür. Auch der Wald tickte, auf seine eigene grüne Art.',
        '„Geh nur“, sagte Ada. „Aber komm zurück, wenn etwas stehen bleibt.“ Und jeden Winter, wenn die Uhren der Stadt langsamer wurden, kam der Fuchs nach Hause.',
      ],
      end: 'Ende',
      back: 'Für alle, die genau hinhören.',
    },
    birds: {
      file: '03-bestimmungsbuch-der-erfundenen-voegel.pdf',
      title: 'Bestimmungsbuch der erfundenen Vögel',
      coverTop: 'BESTIMMUNGSBUCH DER',
      coverTitle: 'Erfundenen Vögel',
      coverSub: 'Zwölf Arten, die du nie sehen wirst',
      introTitle: 'So benutzt du dieses Buch',
      intro:
        'Jeder Vogel in diesem Buch wurde von mindestens einem Menschen beobachtet, der gerade nicht ganz aufgepasst hat. Zu jedem Eintrag steht, wo der Vogel angeblich lebt, wie er angeblich klingt und wann man ihn am besten nicht sieht.\nNotizen am Rand sind ausdrücklich erwünscht. Sichtungen lassen sich nicht bestätigen, aber man kann sich trotzdem über sie freuen.',
      labels: ['Lebensraum', 'Ruf', 'Notizen'],
      sightings: 'Meine Sichtungen:',
      species: [
        ['Teetassen-Grasmücke', 'Küchenfensterbretter, früh am Morgen.', 'Ein leises Klirren, wie ein abgelegter Löffel.', 'Singt nur, kurz bevor der Wasserkessel pfeift.'],
        ['Kleiner Schirmreiher', 'Bushaltestellen bei Nieselregen.', 'Ein papierenes Flattern.', 'Steht auf einem Bein und tut so, als sei er zugeklappt.'],
        ['Haubentagtraum', 'Die letzte Reihe jedes Klassenzimmers.', 'Ein langes, unfertiges Summen.', 'Verschwindet, sobald man seinen Namen laut ausspricht.'],
        ['Bibliothekskauz', 'Zwischen den Regalen ungelesener Bücher.', 'Ein strenges „Pssst“.', 'Nistet in zurückgegebenen Büchern mit Eselsohren.'],
        ['Kupferlaternenfink', 'Häfen in der Abenddämmerung.', 'Ein tiefes, warmes Pfeifen.', 'Seine Federn sollen leuchten, wenn jemand zu spät nach Hause kommt.'],
        ['Papiersegler', 'Über Schreibtischen an offenen Fenstern.', 'Das Rascheln einer umgeblätterten Seite.', 'Zieht jedes Mal weiter, wenn ein Brief verschickt wird.'],
        ['Mitternachtsregenpfeifer', 'Leere Strände bei Neumond.', 'Zwei Töne, dann eine lange Pause.', 'Nur aus dem Augenwinkel zu sehen.'],
        ['Gewöhnlicher Irgendwo-Spatz', 'Überall, wo du gerade nicht bist.', 'Ein fröhliches, fernes Tschilpen.', 'Der am weitesten verbreitete erfundene Vogel.'],
        ['Samtgewittervogel', 'Hügelkuppen vor einem Sturm.', 'Ein Grollen, das man in der Brust spürt.', 'Wird von Kindern öfter gemeldet als von Erwachsenen.'],
        ['Gartenwirrling', 'Unter Hecken, nahe verlorener Handschuhe.', 'Eine verwirrte Frage aus drei Tönen.', 'Sitzt oft genau auf dem, was du gerade suchst.'],
        ['Silberzüngiger Gerüchtevogel', 'Märkte, Treppenhäuser, Türschwellen.', 'Ein Flüstern, das jedes Mal anders klingt.', 'Keine zwei Berichte stimmen überein, was seine Existenz beweist.'],
        ['Stillstunden-Zaunkönig', 'Überall dort, wo jemand liest.', 'Keiner. Er ist die Stille selbst.', 'Wahrscheinlich ist gerade einer in deiner Nähe.'],
      ],
      back: 'Schau weiter nach oben.',
    },
    bread: {
      file: '04-brot-und-salz.pdf',
      title: 'Brot & Salz: Einfache Rezepte',
      coverTitle: 'BROT & SALZ',
      coverSub: 'Einfache Rezepte für gewöhnliche Tage',
      kicker: 'EIN PDBOOK-BEISPIEL',
      contents: 'Inhalt',
      contentsNote: 'Nichts hiervon ist schwierig. Das sind die Rezepte für Tage, an denen man etwas Gutes möchte, ohne viel Aufhebens darum zu machen.',
      ingredients: 'ZUTATEN',
      method: 'ZUBEREITUNG',
      recipes: [
        ['Pfannen-Fladenbrot', 'Für 6 Stück', ['250 g Weizenmehl', '1 TL Salz', '1 TL Backpulver', '150 ml warmes Wasser', '2 EL Olivenöl'],
          ['Mehl, Salz und Backpulver in einer Schüssel mischen.', 'Wasser und Öl dazugeben und rühren, bis ein weicher Teig entsteht.', 'Zwei Minuten kneten und dann 15 Minuten unter einem Tuch ruhen lassen.', 'In sechs Kugeln teilen und jede dünn ausrollen.', 'In einer trockenen, heißen Pfanne etwa eine Minute pro Seite backen, bis sie aufgehen und braune Flecken bekommen.']],
        ['Einfache Tomatensuppe', 'Für 4 Personen', ['2 EL Olivenöl', '1 Zwiebel, gehackt', '2 Knoblauchzehen, in Scheiben', '800 g Tomaten aus der Dose', '500 ml Gemüsebrühe', 'Salz und Pfeffer'],
          ['Die Zwiebel bei mittlerer Hitze 8 Minuten im Öl andünsten.', 'Den Knoblauch dazugeben und eine weitere Minute garen.', 'Tomaten und Brühe hinzufügen und 20 Minuten köcheln lassen.', 'Fein pürieren und abschmecken.', 'Mit Fladenbrot zum Eintunken servieren.']],
        ['Zitronenreis', 'Für 3 Personen', ['200 g Langkornreis', '1 EL Butter oder Öl', '1 Zitrone, Schale und Saft', 'Eine Handvoll Petersilie', 'Salz'],
          ['Den Reis waschen, bis das Wasser klar bleibt.', 'Mit 400 ml Salzwasser zugedeckt bei schwacher Hitze 12 Minuten garen.', 'Vom Herd nehmen und zugedeckt 5 Minuten ziehen lassen.', 'Butter, Zitronenschale und -saft mit einer Gabel unterheben.', 'Mit gehackter Petersilie bestreuen.']],
        ['Ofengemüse', 'Für 4 Personen', ['1 kg gemischtes Gemüse (Karotten, Paprika, Zwiebeln, Kartoffeln)', '3 EL Olivenöl', '1 TL Salz', '1 TL getrockneter Thymian'],
          ['Den Ofen auf 220 °C vorheizen.', 'Das Gemüse in ähnlich große Stücke schneiden.', 'Auf einem großen Blech mit Öl, Salz und Thymian vermengen.', '35 bis 40 Minuten rösten, einmal wenden, bis die Ränder gebräunt sind.']],
        ['Sonntagspfannkuchen', 'Für 8 Stück', ['150 g Weizenmehl', '1 EL Zucker', '2 TL Backpulver', 'Eine Prise Salz', '1 Ei', '200 ml Milch', '1 EL geschmolzene Butter'],
          ['Die trockenen Zutaten verrühren.', 'Ei, Milch und Butter in einem Krug verquirlen.', 'Die flüssigen zu den trockenen Zutaten geben und nur kurz verrühren; ein paar Klümpchen sind in Ordnung.', 'Kellenweise in einer leicht geölten Pfanne backen, bis Blasen erscheinen, dann wenden.', 'Im warmen Ofen warm halten, bis alle fertig sind.']],
        ['Haferkekse', 'Für 16 Stück', ['100 g Butter', '75 g brauner Zucker', '1 EL Honig', '125 g Haferflocken', '100 g Weizenmehl', '1/2 TL Natron'],
          ['Den Ofen auf 180 °C vorheizen und ein Blech mit Backpapier auslegen.', 'Butter, Zucker und Honig zusammen schmelzen.', 'Haferflocken, Mehl und Natron unterrühren.', 'Walnussgroße Kugeln formen und auf dem Blech leicht flach drücken.', '12 Minuten goldbraun backen. Vor dem Essen abkühlen lassen.']],
      ],
      back: 'Einfach kochen. Großzügig teilen.',
    },
    poems: {
      file: '05-kleine-stunden.pdf',
      title: 'Kleine Stunden: Zwölf kurze Gedichte',
      coverTitle: 'Kleine Stunden',
      kicker: 'ZWÖLF KURZE GEDICHTE',
      poems: [
        ['Wasserkessel', 'Bevor das Haus ganz wach ist,\nräuspert sich der Kessel,\nund alles, was ich sagen wollte,\nsteigt auf als Dampf und schwebt davon.'],
        ['Leuchtturm', 'Die ganze Nacht ein einziges Wort\nfür Schiffe, die er nie trifft:\nhier, hier, hier —\nals ob das schon genügte.'],
        ['Bestandsaufnahme', 'Eine Tasse, ein Stuhl, ein Fenster,\neine langsame, geduldige Pflanze.\nIch zähle sie wie ein Kind, das nicht schlafen kann\nund zählt, was ihm noch bleibt.'],
        ['Schnee', 'Der Schnee kam, um zuzuhören.\nEr legte sich auf die Straße\nund hielt den Atem so lange an,\nbis die Stadt vergaß, wohin sie wollte.'],
        ['Zug', 'Um zwei Uhr nachts fährt noch ein Zug,\nund niemand, glaube ich, sitzt darin —\nnur helle Fenster, die das Dunkel\nvon einer Stadt zur nächsten ziehn.'],
        ['Bibliothek', 'Die Bücher schlafen meistens.\nEin paar von ihnen lesen mich.\nIch blättere um, und irgendwo\ndreht sich ein Satz nach mir um.'],
        ['Kleine Stunden', 'Das sind die Stunden, zu klein für Uhren,\ndie man hält und nicht behält:\nder Raum zwischen Gedanke und Wort,\nder Flur hinüber in den Schlaf.'],
        ['Brief', 'Ich habe dir geschrieben und ihn nie abgeschickt.\nEr wartet in einer Schublade,\nwo nie verschickte Briefe lernen,\nwofür Briefe eigentlich da sind.'],
        ['Regen auf dem Dachfenster', 'Jemand tippt auf dem Dach\nin einer Sprache aus Glas.\nIch kann kein Wort davon lesen.\nIch lasse die Absätze vorüberziehn.'],
        ['Motte', 'Die Motte liebt die Lampe\nso, wie ich den Juni liebe:\ntöricht, ganz und gar\nund viel zu früh.'],
        ['Karte', 'Mein Großvater zeichnete Inseln,\nnicht größer als ein Schuh.\nEr sagte, an den kleinsten Orten\nsagt das Meer die Wahrheit.'],
        ['Morgen', 'Und dann kommt das Licht, gewöhnlich,\nund gießt sich ein wie Tee.\nDie Nacht legt ab, was sie gehalten hat.\nUnd endlich tun wir es auch.'],
      ],
      back: 'Lies langsam. Es ist spät.',
    },
  },
};
